# Week 3 Assignment
* Download the "Week_3_Assignment.ipynb" notebook 
* Fill in the code in the cells marked with `# YOUR ANSWER HERE:` by answering the question/task defined in the cell above it starting with `GRADED:`
* Code cells outside of `# YOUR ANSWER HERE:` will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it!

In [26]:
# PLEASE, DO NOT MODIFY THIS CELL!

# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np

# SECtION A data
nparr = np.arange(145, 217).reshape(12, 6)

# data location
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
a_df = pd.read_csv(data_url, header=0)
a_df.head(11)


iata                            airport               city state country  \
0   ORD       Chicago O'Hare International            Chicago    IL     USA   
1   ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2   DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3   PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4   DEN                        Denver Intl             Denver    CO     USA   
5   IAH       George Bush Intercontinental            Houston    TX     USA   
6   SFO        San Francisco International      San Francisco    CA     USA   
7   LAX          Los Angeles International        Los Angeles    CA     USA   
8   MCO              Orlando International            Orlando    FL     USA   
9   CLT    Charlotte/Douglas International          Charlotte    NC     USA   
10  SLC                Salt Lake City Intl     Salt Lake City    UT     USA   

          lat        long    cnt  
0   41.979595  -87.904464  25129  
1   33.640444  -84.426944  21925  
2   32.895951  -97.037200  20662  
3   33.434167 -112.008056  17290  
4   39.858408 -104.667002  13781  
5   29.980472  -95.339722  13223  
6   37.619002 -122.374843  12016  
7   33.942536 -118.408074  11797  
8   28.428889  -81.316028  10536  
9   35.214011  -80.943126  10490  
10  40.788388 -111.977773   9898

## GRADED SECTION A

1. Determine the shape, number of dimensions and type of elements in the numpy array `nparr`
2. Determine the standard deviation of all elements in `nparr`
3. Determine the position (not the value) of the maximum value element in `nparr`
4. Create an array of the same shape as `nparr` but filled with zeros
5. Create an array of the same shape as `nparr` but filled with ones
6. Create an array of the same shape as `nparr` but where all elements are the square root values
7. Create an array result of shape `12` by `12` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`

In [27]:
nparr = np.arange(145, 217).reshape(12, 6)

#1

print("1 ]shape of the array is                        :",nparr.shape)
print("2 ]Dimension of the array element is            :",nparr.ndim)
print("3 ]Type of elements in the numpy array are      :",nparr.dtype)

#2
print("2] Standard deviation is",np.std(nparr))

#3
position_nparr = np.where(nparr == np.amax(nparr))
print("3] positin of maximum value element is",position_nparr[0][0],position_nparr[1][0])

#4.
nparr_ones = np.ones(nparr.shape,dtype=int)
print("5] Array of same shape as nparr filled with ones:   \n",nparr_ones)

#5.
nparr_zeros = np.zeros(nparr.shape, dtype=int,order='C')
print("4] Array of same shape as nparr filled with zeros:  \n",nparr_zeros)


#6.
square_root = np.sqrt(nparr)
print("6] Array of same shape as nparr with all the elements having the square_root :   \n",square_root)

#7.
Multi_array = np.dot(nparr, nparr.T)
print("7] Array created with dimension '12' by '12'   \n",Multi_array)

1 ]shape of the array is                        : (12, 6)
2 ]Dimension of the array element is            : 2
3 ]Type of elements in the numpy array are      : int32
2] Standard deviation is 20.7826049057058
3] positin of maximum value element is 11 5
5] Array of same shape as nparr filled with ones:   
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
4] Array of same shape as nparr filled with zeros:  
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
6] Array of same shape as nparr with all the elements having the square_root :   
 [[12.04159458 12.08304597 12.12435565 12.16552506 12.20655562 12.24744871]
 [12.28820573 12.32882801 12.36931688 12.40967365 12.4498996  12.489996  ]
 [12.52996409 12.56980509 12.60952021 12.6491

## GRADED SECTION B

The dataframe `a_df` loads the dataset that contains information on a number of categories regarding traffic (variable `cnt` represents the actual traffic) at US airports from February 2011.
The dataset has already been loaded for you in the first code cell above.
 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than `10,000` (ideally, you should format the print to put the thousands comma separator--as in `23,400` instead of `23400`
 2. Print the names of all the columns of the dataframe
 3. Print a subset of the dataframe containing the `10th` and the `3rd` rows of the original dataframe (`in that order`).
 4. Which US `state` has the `8th` largest __total__ airport traffic? Please, make sure you use the correct variable as described above.
 5. Which state has the second-most __total__ number of airports (i.e. the second-most amount of airports)?
 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?
 7. What is the total airport traffic for all states that border the state of Massachusetts?


In [30]:
# YOUR SECTION B ANSWER HERE (please use comments to number each of your answers)
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
a_df = pd.read_csv(data_url, header=0)
a_df


dframe = a_df[(a_df['cnt'] > 10000)] #it stores the rows that have cnt>10000
length = len(dframe)
print("1.Printing the number of rows for which traffic values are greater than 10,000 are:",length)
print("1.Printing the number of rows in a subset:\n",dframe)




print("2]Printing the names of columns of the dataframe         : \n",a_df.columns.tolist())


print("3] Printing the Subset containg 10th and 3rd rows of the original dataframe  :\n",a_df.loc[[9,2],:])



Largest_total_A =a_df.groupby(by='state').agg(total_cnt=('cnt',np.sum)).sort_values('total_cnt',ascending=False)
print("4] In the United states which states has the 8th largest total airport traffic   :\n",Largest_total_A.iloc[7,:].name)


A_Airports =a_df.groupby(by='state').count().sort_values('airport',ascending=False)
print("5] The state having the second most number of Airports:",A_Airports.iloc[1,:].name)

#6.
total_Acity = a_df['city'].value_counts().to_frame()
total_Acity = pd.DataFrame(total_Acity)
total_Acity = total_Acity.reset_index()
total_Acity.columns = ['city', 'airports']  # changed the column names
total_Acity = total_Acity[total_Acity['airports'] > 1]

multiple_A_city = a_df.loc[a_df['city'].isin(total_airports_cities['city'])].sort_values(by='cnt', ascending=True)
print('6] Numbers Of the cities that have multiple airports, which one has the less total traffic for all airports \n',multiple_A_city.iloc[[0]])
#7
mass_borders = a_df.loc[(a_df['state'] == 'NY') | (a_df['state'] == 'NH') | (a_df['state'] == 'VT') | (a_df['state'] == 'CT') | (a_df['state']== 'RI')]
#mass
T = mass_borders['cnt'].sum()
print (T)


1.Printing the number of rows for which traffic values are greater than 10,000 are: 10
1.Printing the number of rows in a subset:
   iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   
5  IAH       George Bush Intercontinental            Houston    TX     USA   
6  SFO        San Francisco International      San Francisco    CA     USA   
7  LAX          Los Angeles International        Los Angeles    CA     USA   
8  MCO              Orlando International            Orlando    FL     USA   
9  CLT    Charlotte/Douglas International          Charlotte    NC     USA   

         l